# Generated by Django 2.2.2 on 2019-07-18 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='reporter',
            options={'ordering': ['-id']},
        ),
    ]
